apiVersion: 1

datasources:
  # TimescaleDB (PostgreSQL)
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: postgres:5432
    database: demand_forecasting
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: false
    editable: true

  # InfluxDB v2
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: open-stef
      defaultBucket: power_demand
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
    isDefault: true
    editable: true
